app: appDemo
stage: dev

component: framework
name: nuxtjsDemo

inputs:
  src:
    hook: npm run build
    dist: ./
    exclude:
      - .env
  region: ap-guangzhou
  faas:
    name: ${name}
    runtime: Nodejs10.15
  apigw:
    protocols:
      - http
      - https
    environment: release
  static:
    cos:
      replace: true
      bucket: nuxtjs-demo
