app: appDemo
stage: dev

component: framework
name: eggDemo

inputs:
  framework: thinkphp
  src:
    src: ./
    exclude:
      - .env
  faas:
    name: ${name}
  apigw:
    protocols:
      - http
      - https
