app: appDemo
stage: dev

component: framework
name: laravelDemo

inputs:
  framework: laravel
  src: ./
  region: ap-guangzhou
  faas:
    name: ${name}
    runtime: Php7
    environments:
      - key: APP_ENV
        value: production
  apigw:
    protocols:
      - http
      - https
    environment: release
