app: appDemo
stage: dev

component: framework
name: eggDemo

inputs:
  framework: egg
  src:
    src: ./
    exclude:
      - .env
  faas:
    name: framework-demo
  apigw:
    protocols:
      - http
      - https
